name: MPI CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install mpich
      run: sudo apt install -y mpich
    - name: run
      run: make -f ./makefile
    - name: clean
      run: make clean
